name: Debug workflows demo

on: 
    push:
env:
    USER1: "foo"
    USER2: "bar"

jobs:
    debug-job:
        runs-on: ubuntu-22.04
        steps:
        - name: Step 1 -Checkout Repo
          uses: actions/Checkout@v4
        - name: Step 2 - Set USER1 as USERNAME
          run: |
            echo 'USERNAME=$USER1' >> $GITHUB_ENV
        - name: Step 3 - Print USERNAME
          run: |
            echo 'printing USERNAME env variable from Step 2'
            echo 'USERNAME ======= $USERNAME'
            exit 1
        - name: Step 4 - Print USER2
          run: |
            echo $USER2